// Tests for polycpp::bcrypt_pbkdf::pbkdf.
//
// All vectors below were generated by running upstream `bcrypt-pbkdf@1.0.2`
// (Joyent revision 9ae4b4912099b2dc2ff38ab34934324523ab8025) on Node v24
// against the inputs encoded in each test case. The exact node command used
// to produce them is recorded in `docs/test-plan.md ## Current validation`.

#include <polycpp/bcrypt_pbkdf.hpp>
#include <polycpp/buffer.hpp>

#include <gtest/gtest.h>

#include <future>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

polycpp::Buffer hexToBuffer(const std::string& hex) {
    if (hex.size() % 2 != 0) {
        throw std::runtime_error("hex string has odd length");
    }
    auto hexNibble = [](char c) -> std::uint8_t {
        if (c >= '0' && c <= '9') return static_cast<std::uint8_t>(c - '0');
        if (c >= 'a' && c <= 'f') return static_cast<std::uint8_t>(c - 'a' + 10);
        if (c >= 'A' && c <= 'F') return static_cast<std::uint8_t>(c - 'A' + 10);
        throw std::runtime_error("bad hex");
    };
    std::vector<std::uint8_t> bytes(hex.size() / 2);
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        bytes[i] = static_cast<std::uint8_t>((hexNibble(hex[2 * i]) << 4) | hexNibble(hex[2 * i + 1]));
    }
    return polycpp::Buffer::from(bytes.data(), bytes.size());
}

std::string bufferToHex(const polycpp::Buffer& buf) {
    static constexpr char kHex[] = "0123456789abcdef";
    std::string out(buf.length() * 2, '\0');
    for (std::size_t i = 0; i < buf.length(); ++i) {
        out[2 * i + 0] = kHex[(buf.data()[i] >> 4) & 0xf];
        out[2 * i + 1] = kHex[buf.data()[i] & 0xf];
    }
    return out;
}

}  // namespace

// Adapted from upstream bcrypt-pbkdf@1.0.2 oracle output for
// pbkdf("password","salt", rounds=4, keylen=32).
TEST(Pbkdf, Vector1Rounds4Klen32) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 32);
    EXPECT_EQ(bufferToHex(key),
              "5bbf0cc293587f1c3635555c27796598d47e579071bf427e9d8fbe842aba34d9");
}

// Adapted from upstream oracle: pbkdf("password","salt", 4, 64).
TEST(Pbkdf, Vector2Rounds4Klen64) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 64);
    EXPECT_EQ(bufferToHex(key),
              "5ba4bfc60c7ac272931458407f4c1c4936ea356c55125c5a279b791d65bf9842"
              "d49d7e1b572a9052715ebfa9421e7e949d8f8f19be3284732af1ba28341dd9bf");
}

// Adapted from upstream oracle: pbkdf("password","salt", 8, 64).
TEST(Pbkdf, Vector3Rounds8Klen64) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 8, 64);
    EXPECT_EQ(bufferToHex(key),
              "e1367ec5151a33faac4cc1c144cd23fa15d5548493ecc99b9b5d9c0d3b27bec7"
              "6227ea66088b849b20ab7aa478010246e74bba51723fefa9f9474d6508845e8d");
}

// Adapted from upstream oracle: pbkdf("Lorem ipsum dolor sit amet",
// "0123456789abcdef", 16, 16). The "OpenSSH-style" parameter shape with a
// 16-byte salt and 16 rounds.
TEST(Pbkdf, Vector4Complex) {
    auto password = polycpp::Buffer::from("Lorem ipsum dolor sit amet");
    auto salt = polycpp::Buffer::from("0123456789abcdef");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 16, 16);
    EXPECT_EQ(bufferToHex(key), "561c9de308babcc5b0f2a2045394b5f3");
}

// Adapted from upstream oracle: pbkdf("x","y", 1, 8).
TEST(Pbkdf, Vector5Small) {
    auto password = polycpp::Buffer::from("x");
    auto salt = polycpp::Buffer::from("y");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 1, 8);
    EXPECT_EQ(bufferToHex(key), "8f8a6215af1d2fb5");
}

// Adapted from upstream oracle: pbkdf("password","salt", 4, 40). Confirms
// keylen > HASHSIZE that is not a multiple of HASHSIZE; exercises the
// stride-based interleaving path.
TEST(Pbkdf, Vector6OddKeylen40) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 40);
    EXPECT_EQ(bufferToHex(key),
              "5ba4bfc60c7ac272931458407f4c1c4936ea356c55125c5a279b791d65bf9842"
              "d49d7e1b572a9052");
}

// Adapted from upstream oracle: pbkdf("password","salt", 4, 33). Tests the
// boundary just above HASHSIZE.
TEST(Pbkdf, Vector7Klen33) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 33);
    EXPECT_EQ(bufferToHex(key),
              "5ba4bfc60c7ac272931458407f4c1c4936ea356c55125c5a279b791d65bf9842"
              "d4");
}

// Adapted from upstream oracle: pbkdf("abc","xyz", 2, 16).
TEST(Pbkdf, Vector8Klen16Rounds2) {
    auto password = polycpp::Buffer::from("abc");
    auto salt = polycpp::Buffer::from("xyz");
    auto key = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 2, 16);
    EXPECT_EQ(bufferToHex(key), "50362a6c0ad82b16ab701be5e8905a92");
}

// String overload reaches the same Buffer overload.
TEST(Pbkdf, StringPasswordOverloadMatchesBufferOverload) {
    auto salt = polycpp::Buffer::from("salt");
    auto a = polycpp::bcrypt_pbkdf::pbkdf(std::string("password"), salt, 4, 32);
    auto b = polycpp::bcrypt_pbkdf::pbkdf(polycpp::Buffer::from("password"), salt, 4, 32);
    EXPECT_EQ(bufferToHex(a), bufferToHex(b));
}

// Determinism: the same inputs always produce the same output.
TEST(Pbkdf, Deterministic) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");
    auto a = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 32);
    auto b = polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 32);
    EXPECT_EQ(bufferToHex(a), bufferToHex(b));
}

// Mutating one byte of the salt produces a fully different output (no
// correlated bytes / zero overlap is overwhelmingly unlikely).
TEST(Pbkdf, SaltSensitivity) {
    auto password = polycpp::Buffer::from("password");
    auto salt_a = polycpp::Buffer::from("salt");
    auto salt_b = polycpp::Buffer::from("salu");  // one byte different
    auto a = polycpp::bcrypt_pbkdf::pbkdf(password, salt_a, 4, 32);
    auto b = polycpp::bcrypt_pbkdf::pbkdf(password, salt_b, 4, 32);

    std::size_t equal_bytes = 0;
    for (std::size_t i = 0; i < a.length(); ++i) {
        if (a.data()[i] == b.data()[i]) {
            ++equal_bytes;
        }
    }
    // 32 random bytes have an expected ~0.125 byte coincidence; we expect
    // far fewer than half to match.
    EXPECT_LT(equal_bytes, a.length() / 2);
}

// Concurrent invocations from multiple threads must each produce the correct
// output; this guards against accidental sharing of mutable Blowfish state.
TEST(Pbkdf, ThreadSafety) {
    auto password = polycpp::Buffer::from("password");
    auto salt = polycpp::Buffer::from("salt");

    auto run = [&]() {
        return bufferToHex(polycpp::bcrypt_pbkdf::pbkdf(password, salt, 4, 32));
    };

    std::vector<std::future<std::string>> futures;
    for (int i = 0; i < 4; ++i) {
        futures.push_back(std::async(std::launch::async, run));
    }
    const std::string expected =
        "5bbf0cc293587f1c3635555c27796598d47e579071bf427e9d8fbe842aba34d9";
    for (auto& f : futures) {
        EXPECT_EQ(f.get(), expected);
    }
}

// Constants exposed to the public API match upstream values.
TEST(Pbkdf, ConstantsMatchUpstream) {
    EXPECT_EQ(polycpp::bcrypt_pbkdf::BLOCKS, 8u);
    EXPECT_EQ(polycpp::bcrypt_pbkdf::HASHSIZE, 32u);
}
