// Tests for the inner bcrypt_hash step (polycpp::bcrypt_pbkdf::bcryptHash).
//
// Vector generated by running upstream `bcrypt-pbkdf@1.0.2` (Joyent revision
// 9ae4b4912099b2dc2ff38ab34934324523ab8025) on Node v24:
//   const m = require("bcrypt-pbkdf");
//   const sha512 = require("tweetnacl").lowlevel.crypto_hash;
//   const buf = (s) => new TextEncoder().encode(s);
//   const sha2pass = new Uint8Array(64);
//   const sha2salt = new Uint8Array(64);
//   sha512(sha2pass, buf("password"), 8);
//   sha512(sha2salt, buf("salt"),     4);
//   const out = new Uint8Array(32);
//   m.hash(sha2pass, sha2salt, out);

#include <polycpp/bcrypt_pbkdf.hpp>
#include <polycpp/buffer.hpp>
#include <polycpp/crypto.hpp>

#include <gtest/gtest.h>

#include <stdexcept>
#include <string>
#include <vector>

namespace {

polycpp::Buffer hexToBuffer(const std::string& hex) {
    if (hex.size() % 2 != 0) {
        throw std::runtime_error("hex string has odd length");
    }
    auto hexNibble = [](char c) -> std::uint8_t {
        if (c >= '0' && c <= '9') return static_cast<std::uint8_t>(c - '0');
        if (c >= 'a' && c <= 'f') return static_cast<std::uint8_t>(c - 'a' + 10);
        if (c >= 'A' && c <= 'F') return static_cast<std::uint8_t>(c - 'A' + 10);
        throw std::runtime_error("bad hex");
    };
    std::vector<std::uint8_t> bytes(hex.size() / 2);
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        bytes[i] = static_cast<std::uint8_t>((hexNibble(hex[2 * i]) << 4) | hexNibble(hex[2 * i + 1]));
    }
    return polycpp::Buffer::from(bytes.data(), bytes.size());
}

std::string bufferToHex(const polycpp::Buffer& buf) {
    static constexpr char kHex[] = "0123456789abcdef";
    std::string out(buf.length() * 2, '\0');
    for (std::size_t i = 0; i < buf.length(); ++i) {
        out[2 * i + 0] = kHex[(buf.data()[i] >> 4) & 0xf];
        out[2 * i + 1] = kHex[buf.data()[i] & 0xf];
    }
    return out;
}

}  // namespace

// Verify our SHA-512 (via polycpp::crypto::createHash) matches the values
// produced by tweetnacl.lowlevel.crypto_hash for the same inputs.
TEST(Blowfish, SHA512OfPasswordMatchesUpstream) {
    auto digest = polycpp::crypto::createHash("sha512")
                      .update(polycpp::Buffer::from("password"))
                      .digestBuffer();
    EXPECT_EQ(bufferToHex(digest),
              "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb9"
              "80b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86");
}

TEST(Blowfish, SHA512OfSaltMatchesUpstream) {
    auto digest = polycpp::crypto::createHash("sha512")
                      .update(polycpp::Buffer::from("salt"))
                      .digestBuffer();
    EXPECT_EQ(bufferToHex(digest),
              "2e3fce77cf8c4c7478a96d207c1c39715892cac84a18cbec9b634f4bc22b390b"
              "48cd30a4df2e7ebbaee65c346a662c5be2d12441322f7a4bac821a382c4af091");
}

// The inner bcrypt_hash step against the upstream JS oracle.
TEST(Blowfish, BcryptHashKnownVector) {
    auto sha2pass = hexToBuffer(
        "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb9"
        "80b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86");
    auto sha2salt = hexToBuffer(
        "2e3fce77cf8c4c7478a96d207c1c39715892cac84a18cbec9b634f4bc22b390b"
        "48cd30a4df2e7ebbaee65c346a662c5be2d12441322f7a4bac821a382c4af091");

    auto out = polycpp::bcrypt_pbkdf::bcryptHash(sha2pass, sha2salt);
    EXPECT_EQ(out.length(), polycpp::bcrypt_pbkdf::HASHSIZE);
    EXPECT_EQ(bufferToHex(out),
              "b5730b9a86baf65dd812a20dd20557695ba77f8957cf0203b3799a8e5fe0c08b");
}

// bcryptHash output length is always exactly HASHSIZE.
TEST(Blowfish, BcryptHashOutputLength) {
    polycpp::Buffer empty64 = polycpp::Buffer::alloc(64);
    auto out = polycpp::bcrypt_pbkdf::bcryptHash(empty64, empty64);
    EXPECT_EQ(out.length(), polycpp::bcrypt_pbkdf::HASHSIZE);
}

// Calling bcryptHash twice with identical inputs produces identical output.
// Guards against accidental reliance on per-call state (it caught a real
// bug shape in the upstream JS port: shared module-level BLF_J advancement
// would have made consecutive bcryptHash calls produce different outputs).
TEST(Blowfish, BcryptHashIsDeterministic) {
    auto sha2pass = hexToBuffer(
        "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb9"
        "80b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86");
    auto sha2salt = hexToBuffer(
        "2e3fce77cf8c4c7478a96d207c1c39715892cac84a18cbec9b634f4bc22b390b"
        "48cd30a4df2e7ebbaee65c346a662c5be2d12441322f7a4bac821a382c4af091");

    auto a = polycpp::bcrypt_pbkdf::bcryptHash(sha2pass, sha2salt);
    auto b = polycpp::bcrypt_pbkdf::bcryptHash(sha2pass, sha2salt);
    EXPECT_EQ(bufferToHex(a), bufferToHex(b));
}
